<?php
/**
 * 
 * @file strophe_chat.module initializes XMPP Strophe chat functions
 *
 * strophe_chat_init adds /chat/chat_init.js
 * strophe_chat_page($name) builds chat
 * strophe_chat_theme themes chat
 * strophe_chat_node_access($arg) - possible hook for hook_node_access
 *
 * @see /chat/chat.js
 */

/**
 * Implements hook_menu().
 * Makes a Discussion possible with discussion-with/% MENU_LOCAL_TASK
 */
function strophe_chat_menu() {
  $debug = (bool)variable_get('strophe_debug', '');
  if ($debug) {
        drupal_set_message(t('hook menu strophe_chat_menu'));
      }
  $items['discussion-with/%'] = array(
    'page callback' => 'strophe_chat_page',
    'page arguments' => array(1),
    'access callback' => 'strophe_chat_access',
    'access arguments' => array(1),
    'title' => t('XMPP Discuss with'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Adds chat_init.js and triggers strophe_init()
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function strophe_chat_init() {
  $debug = (bool)variable_get('strophe_debug', '');
  strophe_init();
  if ($debug) {
        drupal_set_message(t('strophe_chat_init'));
      }
  drupal_add_js(drupal_get_path('module', 'strophe') . '/chat/chat_init.js');
}

/**
 * Strophe chat page builder.
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 * @return object theme('chat_room', array('other' => $other));
 */
function strophe_chat_page($name) {
  $debug = (bool)variable_get('strophe_debug', '');
  if ($debug) {
        drupal_set_message(t('hook page strophe_chat_page'));
      }
  $other = array_shift(user_load_multiple(array(), array('name' => $name)));
  include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'strophe') . '/strophe.inc';
  drupal_add_js(drupal_get_path('module', 'strophe') . '/chat/chat.js');
  // creates $xmpp_other to add another strophe_user to chat array in Strophe JS
  // @see strophe.inc, strophe_user 
  // has jid, nickname via drupal $user->name
  $xmpp_other = new strophe_user($other);
  if ($debug) {
        drupal_set_message(t(filter_xss('new user $xmpp_other created strophe_chat_page')));
      }
  drupal_add_js(array(
    'strophe' => array(
      'chat' => array('other' => $xmpp_other->jid),
    ),
  ), array('type' =>
    'setting', 'scope' => JS_DEFAULT));
  // returns theme 
  return theme('chat_room', array('other' => $other));
}

/**
 * Implements hook_theme().
 */
function strophe_chat_theme() {
  $debug = (bool)variable_get('strophe_debug', '');
  if ($debug) {  
        drupal_set_message(t('hook theme strophe_chat_theme'));
      }
  $path = drupal_get_path('module', 'strophe_chat');
  return array(
    'chat_room' => array(
      'path' => "$path/theme",
      'template' => 'chat_room',
      'variables' => array('other' => NULL),
    ),
  );

}

/**
 * Implements hook_node_access().
 */
function strophe_chat_node_access($arg) {
  $debug = (bool)variable_get('strophe_debug', '');
  if ($debug) {  
        drupal_set_message('hook node access strophe_chat_node_access');
      }
  return TRUE;
}
